server:
  port: 8888

spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          uri: ${GIT_URI}
